services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "5000:5000"
    networks:
      - e2e_tests_network
    command: ["pytest"]

  e2e_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e2e_test
    environment:
      - BASE_URL=http://app:5000
    depends_on:
      - application
    networks:
      - e2e_tests_network
    command: ["pytest"]

networks:
  e2e_tests_network:
    driver: bridge