name: calculator_pipeline.yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up docker
        uses: docker/setup-buildx-action@v4

      - name: Docker build image
        run: docker build --no-cache -t ci-cd-app .

      - name: Run unit tests
        run: docker run --rm ci-cd-app

      - name: Start app
        run: docker run -d -p 5000:5000 --name calc-app ci-cd-app

      - name: Clone E2E repository
        run: git clone https://github.com/KarolWeber/ci-cd-tests.git

      - name: Install E2E test dependencies
        run: | 
          python pip install -r ci-cd-tests/requirements.txt

      - name: Run E2E tests
        run: pytest ci-cd-tests/test

      - name: Cleanup Docker containers
        if: always()
        run: docker ps -aq | xargs -r docker rm -f


