name: Calculator unit and E2E tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up docker
        uses: docker/setup-buildx-action@v4

      - name: Docker build image
        run: docker build --no-cache -t ci-cd-app .

      - name: Run unit tests
        run: docker run -d -p 5000:5000 --name test-app ci-cd-app python app/app.py

      - name: Wait for port
        run: |
          for i in {1..15}; do
            nc -z localhost 5000 && echo "Port is open" && exit 0
            echo "Waiting for port..."
            sleep 2
          done
          echo "App did not start"
          docker logs test-app
          exit 1

      - name: Checkout e2e repository
        uses: actions/checkout@v4
        with:
          repository: KarolWeber/ci-cd-tests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ci-cd-tests

      - name: Run e2e
        run: |
          install requirements.txt
          pytest
        env:
          BASE_URL: http://localhost:5000

      - name: Cleanup Docker containers
        if: always()
        run: docker ps -aq | xargs -r docker rm -f


