name: Calculator unit and E2E tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v6

      - name: Docker build image
        run: docker build --no-cache -t ci-cd-app .

      - name: Run unit tests
        run: docker run --rm ci-cd-app pytest

      - name: Create Docker network
        run: docker network create e2e-tests-network || true

      - name: Start application server
        run: |
          docker run -d --name application \
          -p 5000:5000 \
          --network e2e-tests-network \
          ci-cd-app

      - name: Wait for application
        run: |
          echo "Waiting for application..."
          
          for i in {1..20}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "Application is up!"
              break
            fi
            
            echo "Waiting..."
            sleep 2
          done

      - name: Checkout tests repository
        uses: actions/checkout@v6
        with:
          repository: KarolWeber/ci-cd-tests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tests image
        run: docker build -t e2e-tests .

      - name: Run e2e
        run: |
          docker run --rm \
          --network e2e-tests-network \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          -e BASE_URL=http://application:5000 \
          e2e-tests

      - name: Generate Allure report
        uses: andgineer/allure-report@v3.6
        with:
          allure-results: allure-results
          website: gh-pages-dir
          reports-site-path: ""

      - name: Fix allure report link
        run: |
          sudo chown -R $USER:$USER gh-pages-dir
          sed -i 's/#behaviors$/#/' gh-pages-dir/index.html

      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-dir
          publish_branch: gh-pages

      - name: Cleanup Docker containers
        if: always()
        run: docker rm -f application || true


