name: Calculator unit and E2E tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v6

      - name: Set up docker
        uses: docker/setup-buildx-action@v4

      - name: Docker build image
        run: docker build --no-cache -t ci-cd-app .

      - name: Run unit tests
        run: docker run --rm ci-cd-app pytest

      - name: Create Docker network
        run: docker network create e2e-tests-network || true

      - name: Start application server
        run: |
          docker run -d --name application \
          -p 5000:5000 \
          --network e2e-tests-network \ 
          ci-cd-app

      - name: Checkout tests repository
        uses: actions/checkout@v6
        with:
          repository: https://github.com/KarolWeber/ci-cd-tests.git
          path: tests
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tests image
        run: docker build -t e2e-tests .

      - name: Run e2e
        run: |
          docker run --rm \
          --network e2e-tests-network \
          -e BASE_URL=http://application:5000 \
          e2e-tests

      - name: Cleanup Docker containers
        if: always()
        run: docker rm -f test-app || true


